const DesignationList : string[] = [
    'Web Developer',
    'Web Designer',
    'Software Developer',
    'Data Scientist',
    'Logo Designer',
    'Graphics Designer',
    'Artificial Intelligence Developer',
    'Machine Learning Engineer',
    'UI/UX Designer',
    'Mobile App Developer',  
    'Game Developer',
    'Digital Marketing Executive',       
    'Content Writer',         
    'SEO Specialist',
    'Video Editer',
    'Cloud Computing Engineer',
    'Cybersecurity Specialist',
    'QA & Tester',
    'Blockchain Developer',
    'Data Entry Operator',
    'Network Administrator',
    'Database Administrator',
    'Project Manager',
    'DevOps Engineer',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
];

export default DesignationList;